### ISSUE TITLE
webflow-url error processLink

### ISSUE THREAD

**Issue by bitdivision** [sygnaltech/webflow-util#2]
Hi! Thanks for the cool library!

I'm using https://wfu.sygnal.com/docs/webflow-url/query/ by injecting:

```
<!-- Add query parameters to links https://wfu.sygnal.com/docs/webflow-url/query/-->
<script type="module" src="https://cdn.jsdelivr.net/gh/sygnaltech/webflow-util@3.36/src/nocode/webflow-url.js"></script>
<!-- End add query parameters to links -->
```

into the footer.

On page load I see the following error in the console:

```
Uncaught ReferenceError: processLink is not defined
    processAll https://cdn.jsdelivr.net/gh/sygnaltech/webflow-util@3.36/src/modules/webflow-url.js:59
    jQuery 2
        each
        each
    processAll https://cdn.jsdelivr.net/gh/sygnaltech/webflow-util@3.36/src/modules/webflow-url.js:44
    <anonymous> https://cdn.jsdelivr.net/gh/sygnaltech/webflow-util@3.36/src/nocode/webflow-url.js:21
    jQuery 13
        e
        t
        setTimeout handler*Deferred/then/l/<
        c
        fireWith
        fire
        c
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
```

Above is with firefox. And with chrome:
```

S.Deferred.exceptionHook @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
t @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
setTimeout (async)
(anonymous) @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
c @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
fireWith @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
fire @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
c @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
fireWith @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
ready @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
B @ jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2
jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2 Uncaught ReferenceError: processLink is not defined
    at HTMLAnchorElement.<anonymous> (webflow-url.js:59:17)
    at Function.each (jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2:2976)
    at S.fn.init.each (jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2:1454)
    at WfuQuery.processAll (webflow-url.js:44:36)
    at HTMLDocument.<anonymous> (webflow-url.js:21:14)
    at e (jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2:30005)
    at t (jquery-3.5.1.min.dc5e7f18c8.js?site=636afc8860df0b364fa17ac5:2:30307)

```

Is this happening due to the order of `processAll` and `processLink`?

**Comment by bitdivision** [comment]
I tried downgrading to version 3.12 and that started working

**Comment by memetican** [comment]
Thanks @bitdivision I just found that same situation and am rolling out a fix now. It was due to an ES6 library change, and the way it resolves function references differently.

**Comment by memetican** [comment]
Try v3.38, should be fixed.
